### ISSUE TITLE
Is this plugin ready? What are the plans?

### ISSUE THREAD

**Issue by sajidalianjum** [platogo/cordova-plugin-unity-ads#1]
Since there is no readme file, I want to ask if this plugin is ready. It's really great to see a new unity ads plugin for Cordova. All other plugins are pretty outdated. Thanks for working on this.

**Comment by Morathil** [comment]
Hey, yes the plugin is ready.

You can call:
`UnityAds.initialize(UnityAdsGameId: string, testMode: boolean, debugMode: boolean)`
`UnityAds.show(serverId?: string, videoAdPlacementId?: string)`

For `show` both params are optional.
Both functions will return a promise.

FYI: We have an open issue on Android where we sometimes don't get any callback from UnityAds. But Unity is already investigating this.

**Comment by sajidalianjum** [comment]
That's great!!! Thank you. I'll try it soon.
